### ISSUE TITLE
Cannot change wall paper

### ISSUE THREAD

**Issue by dstsmallbird** [pengsrc/BingPaper#1]
System: MacOS Sierra
Version: v0.9.6

Cannot change wall paper, even click Today button.

**Comment by pengsrc** [comment]
OK, I'll check that. Thanks for reporting.

**Comment by dstsmallbird** [comment]
Thx.

**Comment by pengsrc** [comment]
Fixed in version 0.9.7. You can close this issue.

**Comment by dstsmallbird** [comment]
Copy that.
